---
task: "RWC-tatum"

dataloaders:
  
  harmonics_shift: True
  feature_type: "hcqt"
  transform_params:
    hop_length: 256
    fmin: 32.70
    n_bins: 120
    bins_per_octave: 24

  train:
    RWC_train:
      type: "RWC"
      separated: True
      frame_based: False
      with_offset: False
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/train_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

  val:
    RWC_val:
      type: "RWC"
      separated: True
      frame_based: False
      with_offset: False
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/test_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

  test:
    RWC_test:
      type: "RWC"
      separated: True
      frame_based: False
      with_offset: False
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/test_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

model:
  melody:
    name: "ConvTCN"
    input_features: 120
    input_channels: 7
    num_convs: 6
    conv_channels: [64, 32, 32, 32, 32, 1]
    kernel_sizes: [5, 5, 3, 3, 3, 1]
    tcn_channels: [128, 128, 128, 128, 128, 128, 128]
    tcn_kernel: 2

training:
  error_names: ["COnPOff F-value", "COnP F-value", "COn F-value"]
  max_epoch: 100
  learning_rate: 5e-4
  warm_up_steps: 100
  early_stop_monitor: "RWC_val"
  early_stop_patience: 10
  early_stop_index: 1
  early_stop_mode: "max"
  # rest_weight: 2.
  onset_weight: 2.
  loss_weights:
    pitch: 1.
    onset: 1.
    