---
task: "RWC-tatum"

dataloaders:
  
  feature_type: "hcqt"
  transform_params:
    hop_length: 256
    fmin: 32.70
    n_bins: 120
    bins_per_octave: 24

  target_type: "logmelspectrogram"
  target_transform_params:
    n_fft: 2048
    hop_length: 256
    n_mels: 128

  train:
    RWC_train:
      type: "RWC"
      separated: True
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/train_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

  val:
    RWC_val:
      type: "RWC"
      separated: True
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/test_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

  test:
    RWC_test:
      type: "RWC"
      separated: True
      hdf5s_dir: "/n/work1/deng/workspaces/hdf5s/RWC/config=22050.yaml/"
      indexes_path: "/n/work1/deng/workspaces/indexes/RWC/config=22050.yaml/fold_0/test_idx.pkl"
      collate_fn: "tatum_based"
      batch_size: 16

model:
  melody:
    name: "CRNN_melody"
    input_channels: 7
    input_features: 120
    num_convs: 6
    conv_channels: [64, 32, 32, 32, 32, 1]
    kernel_sizes: [5, 5, 3, 3, 3, 1]
  
  rendering:
    name: "Renderer"
    num_harmony: 20
    feature_type: "mel"
    sr: 22050
    n_fft: 2048
    n_mels: 128

  reconst:
    name: "ReconstToy"
          
  language_model:
    name: "Vanila"


training:
  reconst_only: True
  error_names: ["COnPOff F-value", "COnP F-value", "COn F-value", "MSE reconst"]
  max_epoch: 100
  learning_rate: 5e-4
  warm_up_steps: 100
  early_stop_monitor: "RWC_val"
  early_stop_patience: 500
  early_stop_index: 1
  early_stop_mode: "max"
  # rest_weight: 2.
  # onset_weight: 20.
  loss_weights:
    pitch: 0.
    onset: 0.
    reconst: 1.